### ISSUE TITLE
ERR_HTTP2_HEADER_SINGLE_VALUE & Certificate signed by unknown authority

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#111]
First of all, thank you for a great job! Keep it up!

Now to the problem. I'm trying to make a request to street-beat.ru, but I get this two errors:

Error 1
`
2020-12-23T10:27:10.171Z ERROR [node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
  clientError: 'TypeError [ERR_HTTP2_HEADER_SINGLE_VALUE]: Header field "x-content-type-options" must only have a single value',
  context: {}
}
`

Error 2
`
2020-12-22T19:48:44.558Z ERROR [node_modules/@secret-agent/mitm/handlers/HttpRequestHandler] MitmHttpRequest.ProxyToServer.RequestHandlerError {
  request: 'GET: https://cdn1.imshop.io/assets/app/b2.min.css',
  error: 'Error: 2020/12/22 23:48:44 Error on tls handshake with 91.209.77.149:45785. Args main.ConnectArgs{Host:"92.223.124.254", Port:"443", IsSsl:true, Servername:"cdn1.imshop.io", RejectUnauthorized:true, ProxyUrl:"", ClientHelloId:"Chrome83", TcpTtl:0, TcpWindowSize:0, Debug:false}, tlsConn.Handshake error: x509: certificate signed by unknown authority',
  context: {}
}
`

In Replay window page seems like fully loaded, but neither waitForAllContentLoaded nor waitForElement methods are not triggered...

The errors occurs with and without proxy, I am using example code from Usage Example section.
Secret-Agent v1.2.0-alpha.4, nodeJS v14.15.1, macOS Big Sur 11.0.1

**Comment by blakebyrnes** [comment]
Hi @dmzebrov. Thanks for the report and feedback!

I can replicate these. I have a fix for the first one.

The second one has a workaround you can use, but I need to dig in to see why Chrome and Firefox are ok with this certificate authority, but the Go runtime (which is what makes the TLS connection) does not...

To get around Error 2, add MITM_ALLOW_INSECURE=true to your env (either via nodejs code: `process.env.MITM_ALLOW_INSECURE='true';` or via cli: `MITM_ALLOW_INSECURE=true node code/street-beat.ru`). Please note though, this isn't an official flag, just to get you through for now!

**Comment by dmzebrov** [comment]
That's worked, thanks for the quick response! Will fix for the Error 1 be included in the next release? I would like to help you with fixing Error 2, but I don't know Go at all, so I hope for you ☺️

**Comment by blakebyrnes** [comment]
Cool! The fix for error 1 will be in the next release. Should be mid-week. 

I'm not actually sure I can fix Error 2 right now without patching Go. It appears to be a Mac issue they're still working through, and in particular there's a Commodo certificate authority that had a cert expire in may. No one was quite sure how to handle it. It sounds like one problem people run into is the expired authority remaining in your Mac keychain. When Go verifies the new certificate, it gets tripped up with the expired cert (at least, that's what I could make of the Go issues I was poking through).

For now, we're going to simply turn off certificate validation as the default setting. It's less valuable for scraping than when you're putting your sensitive information into a website while browsing. We'll wait for Go to resolve this internally and toggle back on. The net result is likely not noticeable for scraping.
