### ISSUE TITLE
MitmProxy.RequestWithoutSessionId

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#143]
Got this warning, while recursively running (with timeout throttling) instance of Secret Agent.

Iteration goes like this:
1. Create Secret Agent instance with userProfile (if first iteration, userProfile = null);
2. agent.goto(url);
3. Scrape page;
4. agent.close();
5. Recursive call.

After some time this warning appears:
`2021-01-28T11:57:09.227Z WARN [node_modules/@secret-agent/mitm/lib/MitmProxy] MitmProxy.RequestWithoutSessionId { isSSL: true, host: 'example.ru', url: '/', context: {} }
2021-01-28T11:57:09.331Z WARN [node_modules/@secret-agent/mitm/lib/MitmProxy] MitmProxy.RequestWithoutSessionId {
  isSSL: true,
  host: 'example.ru',
  url: '/example',
  context: {}
}`

Full iteration located in try/catch block, but it catches nothing. Iteration just freezes until I restart node process.

Secret agent v1.2.0-alpha.5. MacOS.

**Comment by blakebyrnes** [comment]
@dmzebrov Thanks for the report! I think we found/fixed this same issue while we've been testing out the 1.3 branch. It happens when you cycle back through ports on your local machine that connect between Chrome and the Mitm. Chrome will re-use sockets across requests, and so doesn't always identify which SessionId a socket is authenticated as.

We'll have this included in 1.3, which should be within the next week/week and a half.

**Comment by dmzebrov** [comment]
@blakebyrnes got it! Waiting for v1.3 impatiently! I will try fix this by hands for now.
