### ISSUE TITLE
ConnectionToCore maxConcurrency vs. Core Configuration maxConcurrentAgentsCount

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#152]
I'm finding the docs a little confusing on this point, are these two configuration option names controlling the same thing, or are they different things?

I tried setting a limit of 1 using code like this:

`const agent = new Agent({connectionToCore: {maxConcurrency: 1}});`

However the debug output shows seemingly conflicting results:

> 2021-02-06T04:34:09.784Z INFO [/home/ubuntu/node_modules/@secret-agent/core/index] Core.start {
  options: { maxConcurrency: 1 },
  isExplicitlyStarted: false,
  context: {}
}

> 2021-02-06T04:34:09.856Z INFO [/home/ubuntu/node_modules/@secret-agent/core/lib/GlobalPool] AcquiringChrome {
  activeSessionCount: 0,
  waitingForAvailability: 0,
  maxConcurrentAgentsCount: 10,
  context: {}
}

If I want a limit of 1 agent, do I need to set both types of options to 1?

**Comment by blakebyrnes** [comment]
Hi @A-Posthuman, this blog post we put out might help explain the concurrency a tiny bit: https://github.com/ulixee/secret-agent/discussions/117.

We likely should not include a maxConcurrency option when connecting inside an agent, as you're right, it doesn't make much sense. It's intended more for a connection you might re-use across multiple agents.

Creating a single agent, or using the default agent (`import agent from 'secret-agent') will all get you a single agent controlling a single browser session. You don't need to additionally specify your maximum number of agents in your connection. However, if you are trying to ensure a series of scrapes run sequentially, you have a few options:
1) Simply create one agent at a time in your code, running one after another (no need to send in extra configurations)
2) Use a "Handler" with maxConcurrency set to 1. This will ensure only one agent is running at a time (more below)
3) You could reuse the same agent. It won't cleanly separate your underlying session Replays, but sometimes that's ok!

For what it's worth: the concurrency feature is really for managing 2 things:
1. On your "client", how many agents do you want "Working" at the same time. If you are using the default setup, your client and "core" will both be running on the same machine, so this setting is a bit confusing, but imagine once you have multiple "core" servers out in the wild - you're setting a limit on how many you want to be running at once - you might have 1000 sessions going across 100 machines (each machine having 10 concurrent sessions).
2. On each "core", what maximum number of sessions to allow at a given time. You're kind of saying how many concurrent "browser windows" you want open at a given time, with each window in it's own incognito session. You're controlling resources for "core" because the system will tap out at some point - likely with memory for all the concurrent browsing and messages to control the browser.

**Comment by A-Posthuman** [comment]
Ok yeah that clarifies a lot, thanks! Going to go play with the Handler stuff now, looks interesting.
