### ISSUE TITLE
SA doesn't always fully close itself after some types of errors/crashes

### ISSUE THREAD

**Issue by A-Posthuman** [ulixee/secret-agent#312]
I've noticed on both Windows and Ubuntu several situations where remnants of SA/node/chrome are left running in various combinations. Is the intent to leave SA running on purpose after a script exits, in order to reuse it on future script runs, in order to speed up start times? Or should I always see all SA/node/Chrome processes close after my script finishes? Let me know what is the correct expected behavior.

Sorry I haven't been tracking specific errors or details that lead to this, but I'll try to start paying closer attention after I found some copies of SA running on my Ubuntu test server from 2 days ago that were still eating up mem. Would it be possible to build in some warning when starting a new SA script run if it finds older copies running? Or even have an option to have it close those old copies automatically?

**Comment by blakebyrnes** [comment]
This is a great question that is a bad experience at the moment. This flow is changing significantly in the "@ulixee" changes. But for now:
- SA (replay) is supposed to be open and visible to you on each scrape (if you don't have showReplay off or the SA_SHOW_REPLAY=0 flag).
- node runs a Core process and a script process. Those should shut down if there's no work left to do, but Replay can sometimes launch a new Core to access data it didn't get during the session. It's supposed to shut down that node process when you close down.
- Chrome should be shutting down when a script is complete. I found a few cases in Windows, particularly on headed, where things could stay up that are fixed in the Hero branch. I'm not sure I found all of them.

As I write this... it feels super convoluted. Hopefully you can get the general idea... Also feel much better about the new flows we're working on

**Comment by A-Posthuman** [comment]
Ok, good to hear there are further improvements in the pipeline, looking forward to that release.

So if I'm understanding everything you wrote, in general I should see both the node processes and chrome shut down after my script runs, assuming I don't have Replay going, correct?

If that's correct, then if I see parts of the system not closing down, do you want me to open further issues regarding those and any particular errors that seemed to be related?

**Comment by blakebyrnes** [comment]
`So if I'm understanding everything you wrote, in general I should see both the node processes and chrome shut down after my script runs, assuming I don't have Replay going, correct?`
- Correct

Adding them here would be great.

**Comment by A-Posthuman** [comment]
Just reporting in that the problem of SA not closing in the background still occurs with SA 1.5.5 on Windows. The black cmd prompt window popping up is fixed though.
