### ISSUE TITLE
[QUESTION] How to run this without a browser installed?

### ISSUE THREAD

**Issue by swimclan** [ulixee/secret-agent#407]
Can there be step by step instructions put somewhere to show how to use this library from an entirely server side perspective?  I setup the server Core on a docker container and the client on a docker container, networked them and I get WriteStream errors on the core server.  My intention is to run this from a Digital Ocean cloud server running completely automated without any human intervention.  There is no need for even dom selectors as I am trying to get json data from an API that is 403'ing when I use conventional server-side request libraries.  

Any help is greatly apreciated

**Comment by blakebyrnes** [comment]
Sorry for the delay writing back. SecretAgent depends on installing Chrome, even just to run JSON resources. We have long-term plans to bypass full-chrome for these types of requests, but it is not currently possible.

That said, your setup should work fine. Is the port open between machines? Or is the Core docker container failing because it's trying to connect to Chrome?

**Comment by blakebyrnes** [comment]
Closing for now since we're pretty far from being able to offer this functionality.
